### ISSUE TITLE
Where can I find the logs?

### ISSUE THREAD

**Issue by patelheet30** [f-person/timeow-mac#2]
I'm just wondering if the logs are saved anywhere. It would be great to be able to access my active time period logs so I can hook them up with Google Sheets to track my screen usage

**Comment by f-person** [comment]
`defaults read com.timeow.Timeow` gives you all of the app's saved data. You can also get the data of a specific key, if you want like `defaults read com.timeow.Timeow activePeriods`

**Comment by patelheet30** [comment]
Ah. Perfect. That worked 👍
